name: Android CI

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: run test
      run: ./gradlew test
